services:
  caddy:
    image: caddy:latest
    cap_add:
      - NET_ADMIN
    environment:
      - "DOMAIN=raxen001.xyz"
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - "host.docker.internal:192.168.1.4"
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
