include:
  - ./arr/docker-compose.yml
  - ./apps/docker-compose.yml
  - ./immich/docker-compose.yml
  - ./firefly/docker-compose.yml
  - ./jellyfin/docker-compose.yml
  - ./navidrome/docker-compose.yml
  # - ./caddy/docker-compose.yml
