# https://ubuntuhandbook.org/index.php/2020/05/lid-close-behavior-ubuntu-20-04/
# /etc/systemd/logind.conf.d/no_when_lid_close.conf
[Login]
HandleLidSwitch=ignore
HandleLidSwitchExternalPower=ignore
HandleLidSwitchDocked=ignore
