services:
  mc:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPER_CHANNEL: "experimental"
      MEMORY: 4G
    volumes:
      - "/opt/backup/linuxgsm/new_world:/data"

  mc2:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    ports:
      - "25566:25565"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      PAPER_CHANNEL: "experimental"
      MEMORY: 2G
    volumes:
      - "/opt/backup/linuxgsm/old_world:/data"

  # linuxgsm-killingfloor2:
  #   image: gameservermanagers/gameserver:kf2
  #   restart: unless-stopped
  #   volumes:
  #     - ~/linuxgsm/kf2:/data
  #   network_mode: host

