services:
  navidrome:
    image: deluan/navidrome:latest
    ports:
      - "4533:4533"
    restart: unless-stopped
    env_file: .env
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - navidrome:/data
      - "~/Media/music/:/music:ro"

  feishin:
      image: 'ghcr.io/jeffvli/feishin:latest'
      environment:
          - SERVER_NAME=raven
          - SERVER_LOCK=false
          - SERVER_TYPE=navidrome # navidrome also works
          - SERVER_URL=https://navidrome.raxen001.xyz
          - PUID=1000
          - PGID=1000
          - TZ=Asia/Kolkata
      ports:
          - 9180:9180
      restart: unless-stopped

volumes:
  navidrome:
